### PR TITLE
Reload tableView after cell is moved

### PR DESCRIPTION
**Pull request by mosesoak**
Hi @nyura123 thanks for your work getting custom cells into the tableview, it's been very useful.

A problem I ran into was syncing my data on the react side, and getting the tableview to reload.

This is a partial fix. I also had to rig my TableView so that it would rebuild its `sections` array. To do this I set a fake property on it that I linked to a numeric state, when I increment that state it triggers componentWillReceiveProps.

Maybe you'll have some idea of how to solve that in a cleaner way. The reloadData call here gets the tableview to update itself in sync with the data being changed which seems to work even though it might potentially be a race condition with the react data being updated. Another option is to set up a reloadData hook which I also did, but removed it when I found I could just add this line.

### CODE REVIEW

**Comment by nyura123** [comment]
Hi @mosesoak, it looks like moveRowAtIndexPath doesn't change `sections` itself, it just publishes the javascript "change" event. So it's a bit surprising you needed that reloadData there... If your javascript reacts to the 'change' event and does a setState with new (re-ordered) data, it should just work. Maybe you can add your example to the TableViewDemo? 

I actually initially did a similar trick with the fake property for the `CustomEditableExample`, to handle the "Cancel" action. But then I realized it's not needed if I do a setState on each 'change', so basically the data always has to flow from js -> native. The last commit ("fix editing example") on master shows how it's done now. Let me know if that makes sense!

**Comment by mosesoak** [comment]
Wait so, what state am I supposed to be setting exactly?

**Comment by mosesoak** [comment]
Also, I did add a setState bound to a prop and it didn't make the tableview update itself fully, it did require this reloadData call to make it reorder and update all cell content from data as well.

**Comment by nyura123** [comment]
You're rendering some `<Item>`'s based on some data, right? setState() should just result in `<Item>`'s that reflect the row being moved ( TableViewDemo/CustomEditableExample shows an example of this). what was your setState setting?

**Comment by mosesoak** [comment]
I'm not using `json` data.

Here's my implementation. tempCompletedItems and tempItems are arrays of react-element rows, for now. (Haven't fully gotten it wired up to redux yet.)

```
  constructor(props, context) {
    super(props, context);

    this.state = { triggerChangeProp: 0 }
   this.handleListItemDropped = this.handleListItemDropped.bind(this)
}

  handleListItemDropped(event) {
    const { sourceIndex, destinationIndex } = event;
    const startIndex = Math.min(sourceIndex, destinationIndex)
    const swappedItem = tempItems[destinationIndex]
    tempItems[destinationIndex] = tempItems[sourceIndex]
    tempItems[sourceIndex] = swappedItem
    for (let i=startIndex; i<tempItems.length; i++) {
      const index = i + tempCompletedItems.length
      tempItems[i] = React.cloneElement(tempItems[i], { ...propChanges })
    }
    this.setState({triggerChangeProp: this.state.triggerChangeProp+1})
  }

  render() {
    return (
      <View style={styles.contentContainer}>
        <NavBar titleText="EDIT SCHEDULE" />
        <TableView ref="tableView"
          triggerChangeProp={this.state.triggerChangeProp}
          moveWithinSectionOnly
          onChange={this.handleListItemDropped}
          style={{flex:1}}
          editing={true}
          showsDragIconWhenEditing={false}
          tableViewCellEditingStyle={RNTableViewConsts.CellEditingStyle.None}
          >
          <TableView.Section canEdit={false} canMove={false} style={{height:0}}>
            {tempCompletedItems.map((item, i) => (
              <TableView.Cell key={i} canMove={false} canEdit={false}>
                {item}
              </TableView.Cell>
              ))}
          </TableView.Section>
          <TableView.Section canEdit={true} canMove={false} style={{height:0}}>
            {tempItems.map((item, i) => (
              <TableView.Cell key={tempCompletedItems.length + i} canMove={!item.props.isComplete} canEdit={!item.props.isComplete}>
                {React.cloneElement(item, { isEditing:true, key:tempCompletedItems.length + i })}
              </TableView.Cell>
              ))}
          </TableView.Section>
        </TableView>
    </View>
    );
  }

```

**Comment by nyura123** [comment]
oh ok... so you're using `Cell`s which is actually not using my code at all. reactModuleForCell prop only has effect if you're rendering via `<Item>`'s, like it shows in the examples.

**Comment by nyura123** [comment]
the whole point of this feature is your `<Item>` defines the data (native `sections`), but each data row is displayed by rendering whatever component you specify via reactModuleForCell prop (not the embedded custom `Cell`:)

```
class LargeTableExample extends React.Component {
    render() {
        var numAdditionaItems = 1000;
        var items = [];
        for (var i = 0; i < numAdditionaItems; ++i) {
            items.push(i);
        }
        return (
            <TableView reactModuleForCell="TableViewExampleCell" style={{flex:1}}
                           allowsToggle={true}
                           allowsMultipleSelection={true}
                           tableViewStyle={TableView.Consts.Style.Grouped}
                           onPress={(event) => alert(JSON.stringify(event))}>
                <Section label={"large section - "+numAdditionaItems+" items"} arrow={true}>
                    {items.map((i)=><Item key={i+1}>{i+1}</Item>)}
                </Section>
            </TableView>
        );
    }
}

//Should be pure... setState on top-level component doesn't seem to work
class TableViewExampleCell extends React.Component {
    render(){
        var style = {borderColor:"#aaaaaa", borderWidth:1, borderRadius:3};
        //cell height is passed from <Item> child of tableview and native code passes it back up to javascript in "app params" for the cell.
        //This way our component will fill the full native table cell height.
        if (this.props.data.height !== undefined) {
            style.height = this.props.data.height;
        } else {
            style.flex = 1;
        }
        if (this.props.data.backgroundColor !== undefined) {
            style.backgroundColor = this.props.data.backgroundColor;
        }
        return (<View style={style}><Text>section:{this.props.section},row:{this.props.row},label:{this.props.data.label}</Text></View>);
    }
}

AppRegistry.registerComponent('LargeTableExample', () => LargeTableExample);
AppRegistry.registerComponent('TableViewExampleCell', () => TableViewExampleCell);
```

**Comment by mosesoak** [comment]
Oh okay, I thought I was using your code because I tried reverting to the base repo and his didn't work with my code - could be due to the fact that you've merged a bunch of other code to your repo.

This PR is not super necessary. If you're becoming the primary maintainer of this component you might consider merging it but, it's probably not hurting anyone out there not to.

**Pull request merged**
